---
sidebar: sidebar 
permalink: use/capacity-review-status.html 
keywords: economic efficiency remediate, economic efficiency, capacity planning, forecast, capacity, storage, 
summary: 'Si vos clusters sont actuellement inférieurs ou prévus pour être inférieurs au seuil de capacité de 70 %, le service d"efficacité économique les identifie comme ressources de faible capacité et vous alerte.' 
---
= Vérifiez l'état de planification de la capacité
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Si les actifs de stockage de votre environnement sont actuellement inférieurs ou prévus au seuil de capacité de 90 %, le service d'efficacité économique les identifie comme ressources de faible capacité et vous alerte. En outre, le service d'efficacité économique fournit des recommandations sur la hiérarchisation des données.

Vous pouvez examiner les types de données suivants pour faciliter la résolution du problème de capacité.

* Plateforme
* Pays où se trouve l'actif
* Capacité actuelle et prévue par mois


.Étapes
. Dans le menu de navigation de gauche de BlueXP, sélectionnez *gouvernance* > *efficacité économique* > *planification de la capacité*.
. Sélectionnez *Evaluer les options de stockage* pour la ressource.
. Choisissez l'une des options suivantes :
+
** *Pratiques exemplaires*: Continuer en cliquant sur le lien pour voir les pratiques exemplaires.
** *Données inactives de niveau* : continuer par link:../use/capacity-tier-data.html["tiering des données inactives vers un stockage cloud et libération du stockage"].
** *Aucune action nécessaire*: Continuer par link:../use/capacity-reminders.html["en sélectionnant aucune action et en définissant des rappels à vérifier à nouveau"].



