---
sidebar: sidebar 
permalink: get-started/capacity-setup.html 
keywords: bluexp, economic efficiency remediate, economic efficiency, capacity planning, set reminders for capacity 
summary: 'Pour utiliser le service d"efficacité économique, effectuez quelques étapes pour le configurer.' 
---
= Mettre en place le service d'efficacité économique
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Pour utiliser le service d'efficacité économique, effectuez quelques étapes pour le configurer.

* Révision link:../get-started/prerequisites.html["prérequis"] pour vous assurer que votre environnement est prêt.
* Créez un connecteur dans BlueXP.
* Découvrez le cluster dans BlueXP.


Vous pouvez créer un connecteur directement dans BlueXP et l'utiliser plus tard dans le service d'efficacité économique. Vous pouvez également créer le connecteur au milieu du processus de résolution des risques.

De la même façon, vous pouvez détecter le cluster à l'avance avec BlueXP ou pendant le processus de résolution des risques.



== Créez un connecteur dans BlueXP

Un connecteur BlueXP inclut des informations d'identification pour les machines NetApp ONTAP.

Pour créer un connecteur dans BlueXP avant d'utiliser le service, reportez-vous à la documentation BlueXP qui décrit https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["comment créer un connecteur"^].



== Découvrez le cluster dans BlueXP

La configuration implique notamment l'identification du nom du cluster, de l'adresse IP, du nom d'utilisateur et du mot de passe dans BlueXP.

Pour obtenir des instructions avant d'utiliser le service, reportez-vous à la section https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html["Découvrez les clusters ONTAP sur site"^].
