---
sidebar: sidebar 
permalink: get-started/capacity-setup.html 
keywords: bluexp, economic efficiency remediate, economic efficiency, capacity planning, set reminders for capacity 
summary: 'Pour profiter de l"efficacité économique de BlueXP, effectuez quelques étapes de configuration.' 
---
= Configurez l'efficacité économique de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Pour profiter de l'efficacité économique de BlueXP, effectuez quelques étapes de configuration.

* Révision link:../get-started/prerequisites.html["prérequis"] pour vous assurer que votre environnement est prêt.
* Créez un connecteur dans BlueXP.
* Découvrez le cluster dans BlueXP.


Vous pouvez créer un connecteur directement dans BlueXP et l'utiliser ultérieurement tout en optimisant l'efficacité économique de BlueXP. Vous pouvez également créer le connecteur au cours du processus de résolution des problèmes de capacité.

De même, vous pouvez détecter le cluster à l'avance avec BlueXP ou pendant le processus de résolution de la capacité.



== Créez un connecteur dans BlueXP

Un connecteur BlueXP inclut des informations d'identification pour les machines NetApp ONTAP.

Pour créer un connecteur dans BlueXP avant d'utiliser le service, reportez-vous à la documentation BlueXP qui décrit https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["comment créer un connecteur"^].



== Découvrez le cluster dans BlueXP

La configuration implique notamment l'identification du nom du cluster, de l'adresse IP, du nom d'utilisateur et du mot de passe dans BlueXP.

Pour obtenir des instructions avant d'utiliser le service, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Découvrez les clusters ONTAP sur site"^].
