---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp economic efficiency works, what is economic efficiency, bluexp, hardware refresh, technology refresh, capacity, forecasted capacity, storage, forecast 
summary: Le service BlueXP  Economic Efficiency identifie les clusters dont la capacité est actuellement ou prévue et vous fournit des recommandations sur le Tiering des données. 
---
= Découvrez l'efficacité économique de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
L'efficacité économique de BlueXP  évalue vos ressources de stockage avec une capacité faible, actuelle ou prévue. Ce service fournit des recommandations sur les options de Tiering des données qui répondent aux besoins de votre entreprise.

L'efficacité économique de BlueXP peut vous aider à atteindre les objectifs suivants.

*Planification des capacités*

* Identifiez dans votre environnement les ressources de stockage présentant des capacités faibles.
* Examinez les actifs pour vérifier la capacité actuelle et prévue.




== Avantages de l'efficacité économique de BlueXP

L'efficacité économique de BlueXP offre les avantages suivants :

* Identifie les systèmes qui approchent des événements de cycle de vie pour vous aider à planifier une mise à jour technologique
* Il propose des recommandations de votre conseiller de confiance pour résoudre les problèmes de capacité dans votre environnement
* Réduction du temps passé à planifier un stockage supplémentaire




== Le coût

NetApp ne vous facture pas pour l'utilisation du service.

Si vous décidez de basculer les données inactives vers un stockage cloud, vous devez consulter votre fournisseur cloud pour connaître les frais applicables.



== L'accès

Vous pouvez accéder à cette fonctionnalité soit via BlueXP Economic Efficiency (*gouvernance* > *Economic Efficiency* > *Tech Refresh*), soit via NetApp Digital Advisor (*Tableau de bord* > *widget planification* > *Tech Refresh*).
