---
sidebar: sidebar 
permalink: get-started/prerequisites.html 
keywords: what are bluexp economic efficiency requirements, economic efficiency prerequisites 
summary: Commencez à utiliser BlueXP Economic Efficiency en vérifiant la prise en charge de votre environnement, de votre accès réseau, de votre connexion et de votre navigateur Web. 
---
= Conditions préalables à l'efficacité économique
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Commencez par vérifier que votre environnement opérationnel, votre connexion, votre accès au réseau et votre navigateur Web sont opérationnels.

Pour utiliser le service d'efficacité économique, vous devez vous assurer que votre environnement répond à toutes les exigences.

* Votre environnement doit respecter toutes les exigences de BlueXP, y compris une connexion et un accès au réseau à partir d'un navigateur Web.
+
Faites référence à BlueXP https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Checklist de mise en route"].

* Vous devez disposer d'identifiants d'accès aux clusters.
* Bien qu'il ne s'agisse pas d'une exigence, il est utile que le connecteur BlueXP soit en place et activé et que le système ONTAP soit détecté. Si ce n'est pas le cas, le service vous guide tout au long de ces processus.
* Si vous prévoyez de transférer les données inactives vers un stockage cloud, assurez-vous que le cluster est éligible selon la licence.

