---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: economic efficiency faq, bluexp, economic efficiency frequently asked questions 
summary: 'Le service BlueXP Economic Efficiency identifie les clusters qui ont une faible capacité actuelle ou prévue et vous fournit des recommandations sur le Tiering des données ou la capacité supplémentaire (pour les systèmes AFF). Le service fournit également des recommandations de mise à jour technologique sur les systèmes qui approchent de leur fin de vie.' 
---
= Quoi de neuf
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouveautés de l'efficacité économique de BlueXP.



== 15 mai 2024

Certaines fonctionnalités d'efficacité économique de BlueXP  ont été temporairement désactivées :

* Mise à jour technologique
* Ajoutez de la capacité




== 14 mars 2024

Si vous disposez de ressources existantes et souhaitez déterminer si une technologie doit être mise à jour, vous pouvez utiliser les options de mise à jour technologique d'efficacité économique BlueXP. Vous pouvez soit examiner une courte évaluation de vos workloads actuels et obtenir des recommandations, soit envoyer des journaux AutoSupport à NetApp au cours des 90 derniers jours, le service peut maintenant fournir une simulation des workloads pour voir les performances de vos workloads sur du nouveau matériel.

Vous pouvez également ajouter une charge de travail et exclure des charges de travail existantes de la simulation.

Auparavant, vous pouviez uniquement évaluer vos ressources et déterminer si une mise à jour technologique est recommandée ?

La fonction fait désormais partie de l'option Tech Refresh dans le menu de navigation de gauche.

En savoir plus sur le link:../use/tech-refresh.html["Évaluer une mise à jour technologique"].



== 08 novembre 2023

Cette version de BlueXP Economic Efficiency comprend une nouvelle option qui permet d'évaluer vos ressources et d'identifier si une mise à jour technologique est recommandée. Le service inclut une nouvelle option de mise à jour technologique dans le menu de navigation de gauche, de nouvelles pages sur lesquelles vous pouvez évaluer vos charges de travail et ressources actuelles, ainsi qu'un rapport qui vous fournit des recommandations.



== 02 avril 2023

Le nouveau service d'efficacité économique BlueXP identifie les ressources de stockage dont la capacité est faible, actuelle ou prévue, et fournit des recommandations sur le Tiering des données ou la capacité supplémentaire pour les systèmes AFF sur site.

link:https://docs.netapp.com/us-en/bluexp-economic-efficiency/get-started/intro.html["Découvrez l'efficacité économique de BlueXP"].
